<?php

function og_admin_role_og_membership_update(OgMembership $og_membership) {
    //print_r($og_membership);
    $uid = $og_membership->etid;

    $role_name = 'consortium administrator'; // The name of the role to revoke.
    $role = user_role_load_by_name($role_name);
    if(!$role) {
        watchdog(WATCHDOG_CRITICAL, 'Cannot find consortium admin role!');
        return;
    }
    
    //check if user is community admin of SOME community
    $iscadmin = db_query("select uid from og_users_roles users, og_role role WHERE role.rid=users.rid AND role.name='administrator member' AND users.uid= :uid", array(':uid' => $uid))->fetchField();
    
    if ($iscadmin) {
        user_multiple_role_edit(array($uid), 'add_role', $role->rid);
    } else {
        //revoke permissions
        user_multiple_role_edit(array($uid), 'remove_role', $role->rid);
    }


}
