<?php
/**
 * @file
 * sesi_default_community.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function sesi_default_community_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'group_register'
  $field_bases['group_register'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'group_register',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'no_ui' => TRUE,
    'settings' => array(
      'allowed_values' => array(
        0 => 'Do not show on registration page',
        1 => 'Show on registration page',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  return $field_bases;
}
