<?php

/**
 * Changes the look and feel of the mica query screen
 * Implements hook form_FORM_ID_alter
 * 
 * @param type $form
 * @param type $form_state
 * @param type $form_id 
 */
function query_interface_form_mica_query_edit_form_alter(&$form, $form_state, $form_id) {
    // Make sure the name field is filled (as it is required within mica)
    // and the complete box with metainformation is hidden from the user
    if( array_key_exists( "general", $form ) ) {
        // Add the name hidden field to the form itself
        $nameElement = $form[ "general" ][ "name" ];
        $nameElement[ "#weight" ] = 1;
        $nameElement[ "#type" ] = "hidden";
        
        // Set a default value for the name of the query.
        // This is needed because the name field is required
        if( !$nameElement[ "#default_value" ] ) 
            $nameElement[ "#default_value" ] = "Query " . mktime() . "." . rand(0,10000);
        
        // Remove the fieldset with name, description etc.
        unset( $form[ "general" ] );
        
        // Add name field to an empty 'general' field.
        // This is used because the mica theme only renders a limited
        // list of items to the screen. See the theme_mica_query_edit_form
        // method in mica_query.pages.inc.
        // This can be overridden by registering another theme method
        // See hook_theme_registry_alter method and https://www.drupal.org/node/1621416
        // if you want to change that.
        $form[ "general" ] = array(
            "#type" => "item",
            "name" => $nameElement
        );
    }
    
    // By default, show a list of all variables, with the possibility to add
    // and remove constraints for the variable.
    
    
    return $form;
}
