<?php
/**
 * @file
 * sesi_homepage.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function sesi_homepage_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-page-field_hide_title'
  $field_instances['node-page-field_hide_title'] = array(
    'bundle' => 'page',
    'default_value' => array(
      0 => array(
        'value' => 1,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'display_label' => '',
    'entity_type' => 'node',
    'field_name' => 'field_hide_title',
    'label' => 'Show Title',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 31,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Show Title');

  return $field_instances;
}
