<?php
/**
 * @file
 * sesi_contact_form.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function sesi_contact_form_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'captcha_description';
  $strongarm->value = 'This question is for testing whether or not you are a human visitor and to prevent automated spam submissions.';
  $export['captcha_description'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'captcha_placement_map_cache';
  $strongarm->value = array(
    'contact_site_form' => array(
      'path' => array(),
      'key' => 'actions',
      'weight' => 99,
    ),
  );
  $export['captcha_placement_map_cache'] = $strongarm;

  return $export;
}
