<?php

/**
 * Module: sesi_notifyexpiration
 * Time-bound table view in MICA
 * Add expiration date to user on subscription form to community.
 * Create a cron PHP to check permissions, 1 week before send email to user to notify expiration
 * Jan Pillaerds, 21/11/2014
 */

/**
 * Implements hook_cron().
 * Arguments:
 * no arguments
 * references:
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_cron/7
 * https://api.drupal.org/api/examples/cron_example!cron_example.module/7
 */
function sesi_notifyexpiration_cron() {
  watchdog('sesi_notifyexpiration','Cron executed sesi_notifyexpiration');
}

