<?php

function query_access_rights_access_override($dataset_node, $query, $op = 'update') {
  global $user;

  if (in_array('administrator', $user->roles)) {
    return true;
  }

  $ds_groups = _dataset_access_form_get_intersect_groups($user, $dataset_node->nid);
  foreach($ds_groups as $gid) {
    $roles = og_get_user_roles('group', $gid, $user->uid);
    if(in_array(OG_ADMINISTRATOR_ROLE, $roles)) {
      return true;
    }
  }

  return false;
}
