<?php
module_load_include('inc', 'query_ontologies', 'query_ontologies.taxonomy_tree');

/**
 * Registers urls specific for new query interface 
 * Implements hook_menu().
 */
function query_ontologies_menu() {
    $items = array();
    
    // This URL is used to retrieve the taxonomy tree for a given dataset
    // using ajax
    $items['sesi/node/%node/variable/%node/variabletaxonomy'] = array(
        'title' => 'Taxonomy',
        'access callback' => '_mica_datasets_node_queries_access',
        'access arguments' => array(2, 'view'),        
        'page callback' => 'query_ontologies_variable_taxonomy', 
        'page arguments' => array(4),
        'delivery callback' => 'drupal_json_output',
    );
    
    // This URL is used to retrieve the taxonomy tree for a given dataset
    // using ajax
    $items['sesi/node/%node/variable/%node/variabletaxonomy/%'] = array(
        'title' => 'Taxonomy',
        'access callback' => '_mica_datasets_node_queries_access',
        'access arguments' => array(2, 'view'),        
        'page callback' => 'query_ontologies_variable_taxonomy', 
        'page arguments' => array(4, 6),
        'delivery callback' => 'drupal_json_output',
    );
    
    
    return $items;
}