<?php
/**
 * @file
 * Code for the Sesi Communities and files feature.
 */

include_once 'sesi_communities_and_files.features.inc';

/**
 * Sets 'promote to frontpage' default to false for all 
 * community content types
 * @see module sesi_hook
 */
function sesi_communities_and_files_sesi() {
    $contentTypes = array( 
        "community",
        "community_document",
        "study",
        "dataset",
        "variable",
        "event",
        "article"
    );
    
    echo "Resetting default value for 'promote to frontpage':<br />\n";
    
    foreach( $contentTypes as $contentType ) {
        $optionsKey = "node_options_" . $contentType;
        
        $node_options = variable_get( $optionsKey );
        
        if( !$node_options ) {
            echo "  WARN: Could not retrieve variable options for $contentType. Most probably the setting is already turned off.<br />\n";
        } else {
            $promote_key = array_search('promote', $node_options);
            if ($promote_key !== false) {
                unset($node_options[$promote_key]);
                variable_set($optionsKey, $node_options);
                echo "  Set default value for $contentType  to false<br />\n";
            } else {
                echo "  Default value for $contentType was already set to false<br />\n";
            }
        }
    }
}