<?php
/**
 * @file
 * Code for the Sesi Communities and files feature.
 */

include_once 'sesi_communities_and_files.features.inc';

/**
 * Implements hook_sesi
 * @see module sesi_hook
 */
function sesi_communities_and_files_sesi() {
    $node_options = variable_get( "node_options_community" );
    $promote_key = array_search('promote', $node_options);
    if ($promote_key !== false) {
      unset($node_options[$promote_key]);
      variable_set('node_options_community', $node_options);
    }

    echo "Set default value for community 'promote to front page' to false<br />\n";
}